openstack-cluster:
  controlPlane:
    machineCount: 3

  nodeGroups:
    - name: default-md-0
      machineCount: 2

  nodeGroupDefaults:
    machineFlavor: l3.tiny
    nodeLabels:
      longhorn.demo.io/longhorn-storage-node: true

  cloudCredentialsSecretName: david-prod-cloud-credentials

  addons:
    ingress:
      enabled: true
      nginx:
        release:
          values:
            controller:
              service:
                # test.harbor.stfc.ac.uk
                loadBalancerIP: "130.246.211.223"
