{{- if .Values.nfs.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: training-materials
  namespace: {{.Release.Namespace}}
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  nfs:
    server: "{{ .Values.nfs.ip }}"
    path: "/var/training-materials"
{{- end }}
