apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-deployed-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/stfc/cloud-deployed-apps.git
    targetRevision: Port_jhub
    path: clusters/dev/david-jhub
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: management-apps
    namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
        - name: "argocd"
          chartName: argocd

          # NOTE: each chart needs a valuesFile for this to work 
          # so create one for each chart - even if its empty
          # argocd and all dependencies use the same file "argocd-setup-values.yaml" 
          namespace: argocd
          valueFiles:
            - ../../../clusters/dev/david-jhub/argocd-setup-values.yaml

        - name: "cert-manager"
          chartName: cert-manager
          namespace: cert-manager
          valueFiles:
            - ../../../clusters/dev/david-jhub/argocd-setup-values.yaml

        - name: jupyterhub
          chartName: jupyterhub
          namespace: jupyterhub
          valueFiles:
            - ../../../clusters/dev/david-jhub/jupyter-values.yaml
            - secrets://../../../secrets/dev/david-jhub/jupyterhub-secrets.yaml

  syncPolicy:
    preserveResourcesOnDeletion: true 

  template:
      metadata:
        name: '{{ .name }}'
        namespace: argocd
      spec:
        project: default
        source:
          repoURL: "https://github.com/stfc/cloud-deployed-apps.git"
          targetRevision: Port_jhub
          path: "charts/dev/{{ .chartName }}"
        destination:
            server: https://kubernetes.default.svc
            namespace: "{{ .namespace }}"
        
        # apps are easy to deploy - so we can cascade delete them
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
            allowEmpty: true
          syncOptions:
            - CreateNamespace=true

  templatePatch: |
    spec:
      source:
        helm:
          valueFiles:
          {{- range $valueFile := .valueFiles }}
            - {{ $valueFile | toJson }}
          {{- end }}
