openstack-cluster:
  controlPlane:
    machineCount: 3

  nodeGroups:
    - name: default-md-0
      machineCount: 2

  nodeGroupDefaults:
    machineFlavor: l3.micro

  clusterNetworking:
    externalNetworkId: 0dc30001-edfb-4137-be76-8e51f38fd650 # Dev External network ID

  cloudCredentialsSecretName: staging-management-cloud-credentials

  addons:
    ingress:
      enabled: true
      nginx:
        release:
          values:
            controller:
              service:
                # Temporary for testing DR scenario
                loadBalancerIP: "130.246.211.226"
