openstack-cluster:
  controlPlane:
    machineCount: 5

  nodeGroups:
    - name: default-md-0
      machineCount: 10

  nodeGroupDefaults:
    machineFlavor: l2.small

  cloudCredentialsSecretName: victoria-metrics-test-cloud-credentials

  addons:
    ingress:
      enabled: true
      nginx:
        release:
          values:
            controller:
              service:
                # ingress ip in personal scratch space
                loadBalancerIP: "130.246.211.115"
