jupyterhub:
  hub:
    #remove login for metrics collection
    authenticatePrometheus: false
    config:
      Authenticator:
        # Whilst auto-login would be nice it dumps users at IRIS IAM with no warning
        # this gets users into the habit of blindly accepting sign-in without seeing the service
        auto_login: false
      GenericOAuthenticator:
        # Name for the shiny button
        login_service: "IRIS IAM"
        client_id: <TO_FILL>
        client_secret: <TO_FILL>
        # This is the redirect URL in IAM
        oauth_callback_url: <https://example.com/hub/oauth_callback>
        authorize_url: https://iris-iam.stfc.ac.uk/authorize
        token_url: https://iris-iam.stfc.ac.uk/token
        userdata_url: https://iris-iam.stfc.ac.uk/userinfo
        scope:
          - openid
          # This must be included in the scope when creating a client in IAM
          - preferred_username
          - profile
          - email
        username_claim: preferred_username
        userdata_params:
          state: state
        claim_groups_key: groups
        allowed_groups:
          - <your IAM groups>
        admin_groups:
          - <your IAM groups>
      JupyterHub:
        authenticator_class: generic-oauth
