openstack-cluster:

  nodeGroups:
    - name: default-md-0
      machineCount: 2
    - name: md-1
      machineCount: 1
      machineFlavor: l3.tiny
    - name: md-2
      machineCount: 1
      machineFlavor: l3.nano

  cloudCredentialsSecretName: test-capi-addons-2-cloud-credentials

  addons:
    ingress:
      enabled: true
      nginx:
        release:
          values:
            controller:
              service:
                loadBalancerIP: "130.246.215.233"

 