openstack-cluster:
  controlPlane:
    machineCount: 3

  nodeGroups:
    - name: default-md-0
      machineCount: 2

  nodeGroupDefaults:
    machineFlavor: l3.micro

  cloudCredentialsSecretName: test-argocd-cloud-credentials

  addons:
    ingress:
      enabled: false

