{{- if index .Values "cert-manager" "enabled" -}}
{{- if index .Values "cert-manager" "self-signed" "enabled" -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
spec:
  selfSigned: {}
{{- end }}
{{- end }}
