openstack-cluster:

  cloudName: openstack

  kubeNetwork:
    pods:
      cidrBlocks:
        - 10.0.0.0/13
    services:
      cidrBlocks:
        - 10.8.0.0/13
    serviceDomain: cluster.local

  registryMirrors: { docker.io: ["https://dockerhub.stfc.ac.uk"] }

  apiServer:
    # we have to manually floating ip once argo-cd is setup
    enableLoadBalancer: true
    associateFloatingIP: true
    port: 6443
