harbor:
  externalURL: ""

  internalTLS:
    enabled: true

  expose:
    type: ingress
    tls:
      enabled: true

      # Requires certbot - for development override this to auto
      # and set the secretName to empty
      certSource: secret
      secret:
        secretName: "harbor-tls"

    ingress:
      hosts:
        core: "" # Domain name for Harbor
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "self-signed"

  database:
    type: external
    external:
      host: ""
      port: "5432"
      username: ""
      password: ""
      coreDatabase: ""

  notary:
    # Disable Notary as we don't use it
    enabled: false

  persistence:
    enabled: false
    # These are stored externally, so disable dynamic provisioning
    registry:
      storageClass: "-"
    chartmuseum:
      storageClass: "-"
    database:
      storageClass: "-"
    jobservice:
      storageClass: "-"
    redis:
      storageClass: "-"
    trivy:
      storageClass: "-"

    imageChartStorage:
      disableredirect: false
      type: s3
      s3:
        bucket: "harbor"
        accesskey: ""
        secretkey: ""
        # ceph-gw5.gridpp.rl.ac.uk - Prod
        # ceph-dev-gw3.gridpp.rl.ac.uk - Dev
        regionendpoint: ""
        encrypt: true
        secure: true
        skipverify: false
